services:
  dev-db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=nest
    ports:
      - 5433:5432
    expose:
      - 5432
    networks:
      - nest
  test-db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=nest
    ports:
      - 5434:5432
    expose:
      - 5432
    networks:
      - nest

networks:
  nest: